In [10]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
conn = sqlite3.connect('bookstore.db')

In [17]:
query = """
SElECT * from books
"""
pd.read_sql(query,conn)

,book_id,title,author_id,genre,price,stock,published_year
0,1,Things Fall Apart,1,Literary Fiction,12.99,45,1958
1,2,Arrow of God,1,Literary Fiction,11.99,30,1964
2,3,A Grain of Wheat,2,Historical Fiction,13.99,20,1967
3,4,Petals of Blood,2,Political Fiction,14.99,15,1977
4,5,Purple Hibiscus,3,Literary Fiction,13.50,60,2003
5,6,Half of a Yellow Sun,3,Historical Fiction,14.50,55,2006
6,7,Americanah,3,Contemporary Fiction,15.99,40,2013
7,8,Death and the King's Horseman,4,Drama,10.99,25,1975
8,9,Our Sister Killjoy,5,Literary Fiction,11.50,18,1977
9,10,Second Class Citizen,6,Literary Fiction,12.50,22,1974
10,11,African Psycho,7,Thriller,13.00,35,2003
11,12,We Need New Names,8,Literary Fiction,14.00,28,2013
12,13,Open City,9,Literary Fiction,13.50,33,2011
13,14,The River Between,2,Literary Fiction,10.99,12,1965
14,15,Weep Not Child,2,Literary Fiction,10.50,10,1964

In [18]:
query = """
SElECT * from orders
"""
pd.read_sql(query,conn)

    order_id  customer_id  book_id  quantity  order_date
0          1            1        5         2  2024-01-15
1          2            2        1         1  2024-01-18
2          3            3        6         1  2024-01-20
3          4            4        7         3  2024-02-01
4          5            5       12         1  2024-02-03
5          6            1        6         1  2024-02-10
6          7            6        3         2  2024-02-14
7          8            7        5         1  2024-02-20
8          9            2        7         1  2024-03-01
9         10            8        1         2  2024-03-05
10        11            9       13         1  2024-03-10
11        12            4        2         1  2024-03-12
12        13           10        5         2  2024-03-15
13        14            3        8         1  2024-03-18
14        15           11       11         1  2024-03-22
15        16            1        3         1  2024-04-01
16        17            6        6         2  2024-04-05
17        18            5        7         1  2024-04-08
18        19           12        4         1  2024-04-10
19        20            7        9         1  2024-04-15
20        21            2       14         2  2024-04-20
21        22            4        5         1  2024-04-22
22        23           10        7         1  2024-04-25
23        24            8        6         1  2024-05-01
24        25            3        3         1  2024-05-05

In [16]:
query = """
SELECT books.genre,
    COUNT(orders.order_id) AS total_orders

FROM orders
JOIN books ON orders.book_id = books.book_id
GROUP BY books.genre
ORDER BY total_orders DESC
"""

pd.read_sql(query, conn)

                  genre  total_orders
0      Literary Fiction            11
1    Historical Fiction             7
2  Contemporary Fiction             4
3              Thriller             1
4     Political Fiction             1
5                 Drama             1

In [24]:
import pandas as pd 
from pandasql import sqldf

df = pd.DataFrame(
    {
        'name': ['Martin', 'Lenga', 'Baron'],
        'scores': [30, 40, 55]
    }
)

query = """select * from df"""
results = sqldf(query)
print(results)

     name  scores
0  Martin      30
1   Lenga      40
2   Baron      55

In [28]:

df = pd.DataFrame({
    'name': ['Martin', 'Lenga', 'Baron'],
    'scores': [90, 70, 55]
})

query = """
SELECT *,
    CASE 
        WHEN scores >= 90 THEN 'A'
        WHEN scores >= 80 THEN 'B'
        WHEN scores >= 70 THEN 'C'
        WHEN scores >= 60 THEN 'D'
        ELSE 'FAIL'
    END AS grade
FROM df
"""

# locals() allows sqldf to find 'df' in your local environment
results = sqldf(query, locals())
print(results)

     name  scores grade
0  Martin      90     A
1   Lenga      70     C
2   Baron      55  FAIL