In [1]:
import numpy as np
import pandas as pd

sensor_data = np.random.uniform(15,35, (10, 5))
print(sensor_data)

[[21.51950633 30.65748121 26.89537684 29.7555707  24.13204578]
 [23.85555998 17.38500929 27.86789895 25.35602972 30.46466276]
 [31.22755655 31.94055388 15.24685165 17.75968718 34.2320561 ]
 [32.51981758 24.63341366 26.26653046 24.60065132 30.74840731]
 [18.19210368 23.22902888 29.30189653 22.01619632 17.09718327]
 [16.07657115 27.39370177 30.99516831 20.22762691 18.91040379]
 [28.41873323 15.72251051 24.66460198 30.08963903 21.54309006]
 [27.11183239 23.63300518 24.22107683 15.87282836 28.93724772]
 [29.31511439 25.42980059 27.00570087 21.80860559 17.65873775]
 [18.87252758 32.4262957  31.46372609 30.85949071 23.55800545]]

In [14]:
df = [
    {
        'Morning': [23.43, 31.09, 22.83, 26.83],
        'Afternoon': [28.41, 15.73, 24.66, 30.08],
        'Evening': [18.87, 32.42, 31.46, 30.85],
    }
]
df1 = pd.DataFrame(df)
df1.to_csv('Sensor Data.csv', index=False)

In [15]:
pd.read_csv('Sensor Data.csv').head()

,Morning,Afternoon,Evening
0,"[23.43, 31.09, 22.83, 26.83]","[28.41, 15.73, 24.66, 30.08]","[18.87, 32.42, 31.46, 30.85]"

In [21]:
pd.read_csv('Sensor Data.csv').shape

(1, 3)

In [25]:
df_clean = df1.explode(['Morning', 'Afternoon', 'Evening']).reset_index(drop=True)
print(df_clean)

  Morning Afternoon Evening
0   23.43     28.41   18.87
1   31.09     15.73   32.42
2   22.83     24.66   31.46
3   26.83     30.08   30.85

In [29]:
morning_avg = df_clean['Morning'].mean()
print(morning_avg)

26.044999999999998

In [27]:
df_clean.loc['Avg Morning'] = {'Morning': df_clean['Morning'].mean()}
print(df_clean)

            Morning Afternoon Evening
0             23.43     28.41   18.87
1             31.09     15.73   32.42
2             22.83     24.66   31.46
3             26.83     30.08   30.85
Avg Morning  26.045       NaN     NaN

DATALIFE CYCLE USING SQL

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('students.db')

In [2]:
creating_table = """
CREATE TABLE IF NOT EXISTS students_info(
    student_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT, 
    email TEXT UNIQUE NOT NULL,
    course TEXT NOT NULL,
    profile_pic BLOB
)
"""

conn.executescript(creating_table)

In [3]:
inserting_data = """
INSERT INTO students_info (name, phone, email, course, profile_pic)
VALUES
('Shaleen', '0790288929', 'shaleen@gmail.com', 'Datascience', 'shaleen.png'),
('Zizo', '0743124541', 'zizogmail.com', 'DevOps', 'zizo.png'),
('Tete', '', 'tete@gmail.com', 'Software Engineering', ''),
('Trey', '0732345234', 'trey@gmail.com', '', 'trey.png');
"""
conn.executescript(inserting_data)

In [4]:
pd.read_sql("SELECT * from students_info", conn)

,student_id,name,phone,email,course,profile_pic
0,1,Shaleen,0790288929,shaleen@gmail.com,Datascience,shaleen.png
1,2,Zizo,0743124541,zizogmail.com,DevOps,zizo.png
2,3,Tete,,tete@gmail.com,Software Engineering,
3,4,Trey,0732345234,trey@gmail.com,,trey.png

In [9]:
transformation = """    
    DELETE FROM students_info
    WHERE course = '';

    UPDATE students_info 
    SET phone = '07009028842', 
        profile_pic = 'update.png'
    WHERE student_id = 3;

    UPDATE students_info
    SET course = 'Artificial Intelligence'
    WHERE student_id = 2;
"""
conn.executescript(transformation)

In [10]:
pd.read_sql("SELECT * from students_info", conn)

,student_id,name,phone,email,course,profile_pic
0,1,Shaleen,0790288929,shaleen@gmail.com,Datascience,shaleen.png
1,2,Zizo,0743124541,zizogmail.com,Artificial Intelligence,zizo.png
2,3,Tete,07009028842,tete@gmail.com,Software Engineering,update.png

In [12]:
pd.read_sql("""SELECT COUNT(*) FROM students_info;""", conn)

   COUNT(*)
0         3